name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      
      - name: Build and Export with Next.js
        run: |
          echo "Contents of next.config.ts:"
          cat next.config.ts
          echo "Running build..."
          npm run build
          echo "Checking if 'out' directory exists:"
          if [ -d "out" ]; then
            echo "Directory 'out' exists!"
            echo "Contents of 'out' directory:"
            ls -la out/
            echo "Creating .nojekyll file"
            touch out/.nojekyll
          else
            echo "Directory 'out' does not exist!"
            echo "Contents of current directory:"
            ls -la
            echo "Contents of '.next' directory:"
            ls -la .next/ || echo ".next directory not found"
            echo "Creating out directory and copying required files"
            mkdir -p out
            [ -d ".next/static" ] && cp -r .next/static out/ || echo ".next/static not found"
            [ -d "public" ] && cp -r public/* out/ || echo "public directory not found"
            echo "Contents of created 'out' directory:"
            ls -la out/
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 