name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      
      - name: Build with Next.js
        env:
          GITHUB_ACTIONS: true
          GITHUB_REPOSITORY: ${{ github.repository }}
          NODE_ENV: production
        run: |
          echo "Building with repository: $GITHUB_REPOSITORY"
          # Clean previous builds
          rm -rf .next out
          # Run build
          npm run build
          # Ensure .nojekyll exists
          touch out/.nojekyll
          # Create index.html in root if it doesn't exist
          if [ ! -f "out/index.html" ]; then
            echo "Creating index.html in root directory"
            echo '<meta http-equiv="refresh" content="0;url=app/" />' > out/index.html
          fi
          # List directory to verify
          echo "Contents of 'out' directory:"
          ls -la out/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 