name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      
      - name: Build with Next.js
        env:
          GITHUB_ACTIONS: true
          GITHUB_REPOSITORY: ${{ github.repository }}
          NODE_ENV: production
        run: |
          echo "Building with repository: $GITHUB_REPOSITORY"
          
          # Clean any previous build
          rm -rf .next out
          
          # Run the Next.js build
          npm run build
          
          # Debug - list directories to find where Next.js exported the files
          echo "Directory contents after build:"
          ls -la
          
          # Check if .next directory exists
          if [ -d ".next" ]; then
            echo "Contents of .next directory:"
            ls -la .next/
          fi
          
          # Check if next.js created any exports
          if [ -d "out" ]; then
            echo "Contents of out directory (created by Next.js):"
            ls -la out/
          else
            echo "No 'out' directory found. Creating it manually."
            mkdir -p out
            
            # If .next/static exists, copy it to out/_next/static
            if [ -d ".next/static" ]; then
              echo "Copying .next/static to out/_next/static"
              mkdir -p out/_next
              cp -r .next/static out/_next/
            fi
            
            # Check if .next/server/app exists (for HTML files)
            if [ -d ".next/server/app" ]; then
              echo "Found .next/server/app - copying HTML files"
              find .next/server/app -name "*.html" -exec cp {} out/ \;
            fi
            
            # Copy public directory contents
            if [ -d "public" ]; then
              echo "Copying public directory contents"
              cp -r public/* out/
            fi
            
            # Create minimal index.html if not found
            if [ ! -f "out/index.html" ]; then
              echo "Creating minimal index.html"
              echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>PlantPal</title></head><body><h1>PlantPal Smart Watering System</h1><p>Loading application...</p></body></html>' > out/index.html
            fi
          fi
          
          # Add .nojekyll file to prevent GitHub Pages from ignoring files that begin with an underscore
          touch out/.nojekyll
          
          # Show final output directory contents
          echo "Final contents of out directory:"
          ls -la out/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 